name: Build and Deploy Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  amplify_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
          cache: npm

      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli
          amplify configure # Configure your Amplify settings if needed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1 # Adjust the region if needed!!

      - name: Verify Amplify CLI
        run: |
          amplify --version

      - name: Make script executable
        run: |
          chmod +x ./scripts/github_action_script.sh

      - name: Run Amplify Build
        run: ./scripts/github_action_script.sh dlgx5vu2j8upd main
    
        env:
          aws_app_id: dlgx5vu2j8upd
          branch_name: main
          
  next_job:
    runs-on: ubuntu-latest
    needs: amplify_build # This job depends on the "amplify_build" job
    if: success() # This job will run only if "amplify_build" succeeds!
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3   # MUST checkout repository first!

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
          host: SearchNodeALB-325611644.us-east-1.elb.amazonaws.com # In case of 3 node cluster in aws we should point this to the ALB endpoint
          
          # The port Typesense server is listening.
          port: 8108
          protocol: http          
          # The path to  DocSearch config file.
          config: docsearch.config.json
